--Sequences
CREATE SEQUENCE GEN_PEDIDO;
CREATE SEQUENCE GEN_PEDIDO_ITEM;

ALTER SEQUENCE GEN_PEDIDO RESTART WITH 1;
ALTER SEQUENCE GEN_PEDIDO_ITEM RESTART WITH 1;

--Triggers
CREATE TRIGGER PEDIDO_ITEM_BI FOR PEDIDO_ITEM
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF ((NEW.ID IS NULL) OR (NEW.ID = 0))  THEN
    NEW.ID = GEN_ID(GEN_PEDIDO_ITEM,1);
END;

CREATE TRIGGER PEDIDO_BI FOR PEDIDO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF ((NEW.NUMERO_PEDIDO IS NULL) OR (NEW.NUMERO_PEDIDO = 0)  ) THEN
    NEW.NUMERO_PEDIDO = GEN_ID(GEN_PEDIDO,1);
END;

-- Tabelas
CREATE TABLE CLIENTE (
  CODIGO INTEGER NOT NULL PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  CIDADE VARCHAR(50),
  UF CHAR(2)
);

CREATE TABLE PRODUTO (
  CODIGO INTEGER NOT NULL PRIMARY KEY,
  DESCRICAO VARCHAR(200) NOT NULL,
  PRECO_VENDA NUMERIC(15,2) NOT NULL
);

CREATE TABLE PEDIDO (
  NUMERO_PEDIDO INTEGER NOT NULL PRIMARY KEY,
  DATA_EMISSAO TIMESTAMP NOT NULL,
  CODIGO_CLIENTE INTEGER NOT NULL,
  VALOR_TOTAL NUMERIC(15,2) NOT NULL,
  CONSTRAINT FK_PEDIDO_CLIENTE
    FOREIGN KEY (CODIGO_CLIENTE)
    REFERENCES CLIENTE (CODIGO)
);

CREATE TABLE PEDIDO_ITEM (
  ID INTEGER NOT NULL PRIMARY KEY,
  NUMERO_PEDIDO INTEGER NOT NULL,
  CODIGO_PRODUTO INTEGER NOT NULL,
  QUANTIDADE NUMERIC(15,2) NOT NULL,
  VLR_UNITARIO NUMERIC(15,2) NOT NULL,
  VLR_TOTAL NUMERIC(15,2) NOT NULL,
  CONSTRAINT FK_PEDIDO_ITEM_PEDIDO
    FOREIGN KEY (NUMERO_PEDIDO)
    REFERENCES PEDIDO (NUMERO_PEDIDO),
  CONSTRAINT FK_PEDIDO_ITEM_PRODUTO
    FOREIGN KEY (CODIGO_PRODUTO)
    REFERENCES PRODUTO (CODIGO)
);

--Indices
CREATE INDEX IDX_PEDIDO_CLIENTE ON PEDIDO (CODIGO_CLIENTE);
CREATE INDEX IDX_PEDIDO_ITEM_NUMERO_PEDIDO ON PEDIDO_ITEM (NUMERO_PEDIDO);
CREATE INDEX IDX_PEDIDO_ITEM_PRODUTO ON PEDIDO_ITEM (CODIGO_PRODUTO);

--Inserts de teste
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (1, 'José Silva', 'São Paulo', 'SP');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (2, 'Ana Souza', 'Rio de Janeiro', 'RJ');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (3, 'Carlos Lima', 'Curitiba', 'PR');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (4, 'Maria Pereira', 'Belo Horizonte', 'MG');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (5, 'Pedro Oliveira', 'Porto Alegre', 'RS');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (6, 'Fernanda Costa', 'Fortaleza', 'CE');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (7, 'Lucas Alves', 'Manaus', 'AM');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (8, 'Paula Rodrigues', 'Recife', 'PE');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (9, 'Marcos Castro', 'Belém', 'PA');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (10, 'Juliana Nogueira', 'São Bernardo do Campo', 'SP');

INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (1, 'Caneta Azul', 1.20);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (2, 'Caderno Escolar', 12.50);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (3, 'Tesoura', 5.75);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (4, 'Borracha', 0.90);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (5, 'Apontador', 2.50);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (6, 'Régua 30cm', 3.30);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (7, 'Calculadora', 45.99);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (8, 'A4 500 Folhas', 31.97);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (9, 'Kit Transferidor Esquadro Compasso', 35.19);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (10, 'Lápis de Cor - 12 Cores', 14.43);

